package day13.part2

fun main(args: Array<String>) {
    val walker = Walker()
    assert(walker.scanPosition(4, 0) == 0)
    assert(walker.scanPosition(4, 1) == 1)
    assert(walker.scanPosition(4, 2) == 2)
    assert(walker.scanPosition(4, 3) == 3)
    assert(walker.scanPosition(4, 4) == 2)
    assert(walker.scanPosition(4, 5) == 1)
    assert(walker.scanPosition(4, 6) == 0)
    assert(walker.scanPosition(4, 7) == 1)
    assert(walker.scanPosition(4, 8) == 2)
    assert(walker.scanPosition(4, 9) == 3)
    assert(walker.scanPosition(4, 10) == 2)
    assert(walker.scanPosition(4, 11) == 1)
    assert(walker.scanPosition(4, 12) == 0)
    assert(walker.scanPosition(6, 0) == 0)
    assert(walker.scanPosition(6, 1) == 1)
    assert(walker.scanPosition(6, 2) == 2)
    assert(walker.scanPosition(6, 3) == 3)
    assert(walker.scanPosition(6, 4) == 4)
    assert(walker.scanPosition(6, 5) == 5)
    assert(walker.scanPosition(6, 6) == 4)
    assert(walker.scanPosition(6, 7) == 3)
    assert(walker.scanPosition(6, 10) == 0)
    assert(walker.scanPosition(5, 0) == 0)
    assert(walker.scanPosition(5, 1) == 1)
    assert(walker.scanPosition(5, 2) == 2)
    assert(walker.scanPosition(5, 3) == 3)
    assert(walker.scanPosition(5, 4) == 4)
    assert(walker.scanPosition(5, 5) == 3)
}